In [1]:
import torch

In [4]:
# pytorch uses tensor not numpy arrays
x = torch.empty(2,3) # parameter = number of values in tensor
print(x)

tensor([[2.5226e-19, 3.0885e-41, 2.5012e-19],
        [3.0885e-41, 4.4842e-44, 0.0000e+00]])


In [9]:
x = torch.rand(2,2) # by default data type would be float
x

tensor([[0.9246, 0.0412],
        [0.5422, 0.8380]])

In [10]:
x.size()

torch.Size([2, 2])

In [6]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [7]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [8]:
torch.ones(2, 2, dtype = torch.int)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [16]:
torch.tensor([[2.5, 3],[2.5, 3]])

tensor([[2.5000, 3.0000],
        [2.5000, 3.0000]])

# Operations

In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x,y

(tensor([[0.3525, 0.4265],
         [0.9383, 0.0170]]),
 tensor([[0.0991, 0.5346],
         [0.2762, 0.9501]]))

In [20]:
x+y # element wise addition, also can do torch.add(x,y), torch.sub, torch.mul

tensor([[0.4516, 0.9611],
        [1.2145, 0.9671]])

# Inplace operations

In [21]:
# inplace addition or the addition will change the variable
# all functions with "_" does inplace
y.add_(x)

tensor([[0.4516, 0.9611],
        [1.2145, 0.9671]])

# Slicing operations

In [22]:
# slicing operations
x = torch.rand(5,3)
x

tensor([[0.8506, 0.3437, 0.8123],
        [0.4783, 0.3072, 0.2884],
        [0.1011, 0.2322, 0.6806],
        [0.9951, 0.2715, 0.6688],
        [0.6174, 0.3537, 0.0330]])

In [23]:
x[:, 0] # row, column

tensor([0.8506, 0.4783, 0.1011, 0.9951, 0.6174])

In [24]:
x[1,1]

tensor(0.3072)

In [25]:
x[1,1].item()

0.3072124123573303

# Reshape

In [26]:
x

tensor([[0.8506, 0.3437, 0.8123],
        [0.4783, 0.3072, 0.2884],
        [0.1011, 0.2322, 0.6806],
        [0.9951, 0.2715, 0.6688],
        [0.6174, 0.3537, 0.0330]])

In [30]:
x.view(15) # because x size is 5,3. we can out all the values in 1 dimension

tensor([0.8506, 0.3437, 0.8123, 0.4783, 0.3072, 0.2884, 0.1011, 0.2322, 0.6806,
        0.9951, 0.2715, 0.6688, 0.6174, 0.3537, 0.0330])

In [33]:
x.view(-1, 3) # -1 cause we are reshaping, 3 would be column

tensor([[0.8506, 0.3437, 0.8123],
        [0.4783, 0.3072, 0.2884],
        [0.1011, 0.2322, 0.6806],
        [0.9951, 0.2715, 0.6688],
        [0.6174, 0.3537, 0.0330]])

In [34]:
x.view(-1, 5)

tensor([[0.8506, 0.3437, 0.8123, 0.4783, 0.3072],
        [0.2884, 0.1011, 0.2322, 0.6806, 0.9951],
        [0.2715, 0.6688, 0.6174, 0.3537, 0.0330]])

# Numpy to torch and vice-versa

In [35]:
import numpy as np

In [36]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [37]:
# if tensor is in cpu, the new numpy array will only have a reference
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [38]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [39]:
torch.from_numpy(b) # by default data type will be float64

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [42]:
# check cuda
torch.cuda.is_available()

False

In [44]:
# to pass it in gpu
# x = torch.ones(5, device = torch.device("cuda")) or x.to(device)
# numpy can only handle cpu tensor

In [46]:
x = torch.ones(5, requires_grad = True) # calculate gradient for later to optimize
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)